kind = "web"
previewPath = "/"
title = "Sentrix Bot"
version = "1.0.0"
id = "artifacts/sentrix-web"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25944

[services.development]
run = "pnpm --filter @workspace/sentrix-web run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sentrix-web", "run", "build" ]
publicDir = "artifacts/sentrix-web/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25944"
BASE_PATH = "/"
